# Site
title:              Gustav Andersson
description:        "Personal page with blog and other goodies by Gustav Andersson. Created with Jekyll."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ga222ex.github.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    comments: false
    author: Gustav Andersson

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   ga222ex

# Social
analytics-id:       "default"
twitter:            ""
facebook:           knusetorsken
instagram:          ""
github:             ga222ex

# personal
location:           Stockholm, Sweden
phone:              Send me a message first!
email:              ga222ex@student.lnu.se

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]

# Gustav settings
timezone: Europe/Stockholm
